apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: weseek/growi:7.2.4
          name: app
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch:9200/growi
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: growi-secrets
                  key: mongo-uri
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: growi-secrets
                  key: password-seed
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: growi-secrets
                  key: secret-token
            - name: AUDIT_LOG_ENABLED
              value: "true"
            - name: AI_ENABLED
              value: "false"
            - name: APP_SITE_URL
              value: https://growi.kimateku.com
          volumeMounts:
            - name: growi-up-files
              mountPath: /data
      volumes:
        - name: growi-up-files
          persistentVolumeClaim:
            claimName: up-file
