---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-up-files-v2
  namespace: growi
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: growi
    name: up-file
  hostPath:
    path: /data/growi/uploaded_files
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: up-file
  namespace: growi
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-up-files-v2
