apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: weseek/growi:7.2.4
          name: app
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch:9200/growi
            - name: MONGO_URI
              value: mongodb://growiuser:mUHw32hTTEaZ@mongo:27017/growi
            - name: PASSWORD_SEED
              value: kimateku-growi-seed-2025
            - name: SECRET_TOKEN
              value: KimaTeku2025GrowiSecretToken123
            - name: AUDIT_LOG_ENABLED
              value: "true"
            - name: AI_ENABLED
              value: "false"
          volumeMounts:
            - name: growi-up-files
              mountPath: /data
      volumes:
        - name: growi-up-files
          persistentVolumeClaim:
            claimName: up-files
