---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: up-file
  namespace: growi
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
