---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: growi
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-config
  namespace: growi
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
