---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es
  namespace: growi
  labels:
    app: growi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Use default storage class
  resources:
    requests:
      storage: 10Gi
