apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: growi-ingress
  namespace: growi
  annotations:
    cert-manager.io/cluster-issuer: le-cf-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: growi.kimateku.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3000
  tls:
    - hosts:
        - growi.kimateku.com
      secretName: growi-kimateku-tls

