apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-deployment.yaml
  - app-inf.yaml
  - app-service.yaml
  - app-nodeport.yaml
  - db-inf.yaml
  - elasticsearch-deployment.yaml
  - elasticsearch-service.yaml
  - es-conf.yaml
  - es-inf.yaml
  - ingress.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - secret.yaml
labels:
  - includeSelectors: true
    pairs:
      app: growi
