apiVersion: v1
kind: Secret
metadata:
  name: growi-secrets
  namespace: growi
type: Opaque
data:
  # base64 encoded values
  # echo -n 'mUHw32hTTEaZ' | base64
  mongo-password: bVVIdzMyaFRURWFa
  # echo -n 'growiuser' | base64
  mongo-username: Z3Jvd2l1c2Vy
  # echo -n 'mongodb://growiuser:mUHw32hTTEaZ@mongo:27017/growi?authSource=admin' | base64
  mongo-uri: bW9uZ29kYjovL2dyb3dpdXNlcjptVUh3MzJoVFRFYVpAbW9uZ286MjcwMTcvZ3Jvd2k/YXV0aFNvdXJjZT1hZG1pbg==
  # echo -n 'kimateku-growi-seed-2025' | base64
  password-seed: a2ltYXRla3UtZ3Jvd2ktc2VlZC0yMDI1
  # echo -n 'KimaTeku2025GrowiSecretToken123' | base64
  secret-token: S2ltYVRla3UyMDI1R3Jvd2lTZWNyZXRUb2tlbjEyMw==
